name: Artillery Load Test Trigger

on:
  push:
    branches:
      - main
 
jobs:
  artillery:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: lts/*
            
      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
 
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run artillery-test.yml --output ./report.json --name TestFromYouTubeWithPlaywright --record --key ${{ secrets.API_KEY_ARTILLERY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: artillery-report
          path: ./report.json