name: Artillery Playwright Test

on:
  push:
    branches: [ main ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Artillery Test
        run: npx artillery run artillery-test.yml --output ./report.json --name TestFromYouTubeWithPlaywright --record --key ${{ secrets.API_KEY_ARTILLERY }}
